config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands do
    resources :albums, only: [:new]
  end
  resources :albums, only: [:create, :edit, :show, :update, :destroy]

end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint(8)        not null, primary key
#  title      :text             not null
#  year       :integer          not null
#  live?      :boolean          default(FALSE)
#  band_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord
  validates :title, :year, :band_id, presence: true
  validates :live?, inclusion: { in: [true, false] }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint(8)        not null, primary key
#  name       :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true, uniqueness: true

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :text             not null
#  password_digest :text             not null
#  session_token   :text             not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :session_token, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  attr_reader :password

  def generate_session_token
    @session_token = SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    user && user.is_password?(password) ? user : nil
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def new
    @band = Band.find(params[:band_id])
    render :new
  end

  def create
    @album = Album.new(album_params)
    debugger
    if @album.save
      redirect_to band_url(@album.band_id)
    else
      render json: @album.errors.full_messages
    end
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end

  private

  def album_params
    params.require(:albums).permit(:title, :year, :band_id, :live?)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?, :log_in_user

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil 
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
    render :index
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash[:errors] = @band.errors.full_messages
      redirect_to new_band_url
    end
  end

  def new
    render :new
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def update
    @band = Band.find(params[:id])

    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash[:errors] = @band.errors.full_messages
      redirect_to edit_band_url
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy!
    redirect_to bands_url
  end

  private

  def band_params
    params.require(:bands).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
      params[:users][:email],
      params[:users][:password]
    )

    unless user.nil?
      login(user)
      redirect_to bands_url
    else
      flash[:errors] = ["Invalid login credentials!!!"]
      redirect_to new_session_url
    end
  end

  def destroy
    logout
    redirect_to bands_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find_by(params[:id])
    render :show
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to bands_url
      # render :show
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_url
    end
  end



  private

  def user_params
    params.require(:users).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
      "<input type='hidden'
      name='authenticity_token'
      value='#{form_authenticity_token}'/>".html_safe
  end
end

app/views/albums/new.html.erb
<h1>New <%= @band.name %> Album Page!!!</h1>

<form action="<%= albums_url %>" method="post">
  <%= auth_token %>

  <label>Band:
    <select name="albums[band_id]">
      <% Band.all.each do |band| %>
      <option value="<%= band.id %>"><%= band.name %></option>
      <% end %>
    </select>
  </label><br>

  <label>Title:
    <input type="text" name="albums[title]" value="">
  </label><br>

  <label>Year:
    <input type="integer" name="albums[year]" value="">
  </label><br>

  <label>Recording:
    <input type="radio" name="albums[live?]" value="false" > Studio
    <input type="radio" name="albums[live?]" value="true" > Live
  </label><br>

  <input type="submit" value="Add Album">

</form>

app/views/bands/edit.html.erb
<h1>Edit This Band!!!</h1>

<%= @band.name %><br>

<%= flash[:errors] %>

<br><br>

<form action="<%= band_url %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= auth_token %>
  <label>Change Name:
    <input type="text" name="bands[name]" value="">
  </label>
  <br>
  <input type="submit" value="Update Band">
</form>

app/views/bands/index.html.erb
<h1>All Bands Page!!!</h1>

<form action="<%= new_band_url %>" method='get'>
  <%= auth_token %>
  <input type="submit" value="Add Band">
</form>
<br><br>

<% @bands.each do |band| %>
  <li><%= band.name %></li>
  <form action="<%= band_url(band) %>" method='get'>
    <%= auth_token %>
    <input type="submit" value="View Band">
  </form>
  <form action="<%= edit_band_url(band) %>" method='get'>
    <%= auth_token %>
    <input type="submit" value="Edit Band">
  </form>
  <form action="<%= band_url(band) %>" method='post'>
    <input type="hidden" name="_method" value="delete">
    <%= auth_token %>
    <input type="submit" value="Destroy Band">
  </form>
<% end %>

app/views/bands/new.html.erb
<h1>New Band Page!!!</h1>


<%= flash[:errors] %>


<form action="<%= bands_url %>" method="post">
  <%= auth_token %>
  <label>
    <input type="text" name="bands[name]" value="">
  </label>
  <br>
  <input type="submit" value="Add New Band">
</form>

app/views/bands/show.html.erb
<h1>Show Band Page!!!</h1>

<li>Name: <%= @band.name %></li>

<form action="<%= edit_band_url %>" method='get'>
  <%= auth_token %>
  <input type="submit" value="Edit Band">
</form>

<form action="<%= bands_url %>" method='post'>
  <input type="hidden" name="_method" value="delete">
  <%= auth_token %>
  <input type="submit" value="Destroy Band">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav><h1>My Music App</h1></nav>
    <% if logged_in? %>
      <nav>
        </form>
        <div class='user-detail'>
          <p>Welcome: <%= current_user.email %></p>

        <form action="<%= bands_url %>" method="get">
          <%= auth_token %>
          <input type="submit" value="Home Page">
        </form>

        <form action="<%= session_url %>" method='post'>
          <input type="hidden" name="_method" value="delete">
          <%= auth_token %>
          <input type="submit" value="Log Out">
        </form>

        </div>
      </nav>
    <% else %>
      <nav>
        <form action="<%= bands_url %>" method="get">
          <%= auth_token %>
          <input type="submit" value="Home Page">
        </form>

        <div class='user-detail'>
        <form action="<%= new_session_url %>" method='get'>
          <%= auth_token %>
          <input type="submit" value="Log In">
        </form>

        <form action="<%= new_user_url %>" method="get">
          <%= auth_token %>
          <input type="submit" value="Sign Up">
        </form>
        </div>
      </nav>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<% if type == :login %>
  <% action_url = session_url %>
  <% button_label = 'Log in.' %>
<% elsif type == :new_user %>
  <% action_url = users_url %>
  <% button_label = 'Create user.' %>
<% end %>

<form action="<%= action_url %>" method="post">
  <%= auth_token %>

  <label>Email:
    <input type="text" name="users[email]" value="">
  </label>
  <br><br>

  <label>Password:
    <input type="password" name="users[password]" value="">
  </label>
  <br><br>

  <input type="submit" value=" <%= button_label %>">
</form>

app/views/users/new.html.erb
<h1>Make a new user!</h1>

<%= flash[:errors] %>
<br>

<form action="<%= users_url %>" method="post">
  <%= auth_token %>

  <label>Email:
    <input type="text" name="users[email]" value="">
  </label>
  <br><br>

  <label>Password:
    <input type="password" name="users[password]" value="">
  </label>
  <br><br>

  <input type="submit" value="Create User">
</form>

app/views/users/show.html.erb
<h1>Show User Page!!!</h1>

<li>Email: <%= @user.email %></li>